POST https://localhost:7131/messages
Content-Type: application/json

{
  "message": "Hello from ApiOne"
}


### 

# ApiTwo will sum up the numbers - 

POST https://localhost:7131/math
Content-Type: application/json

{
 "numbers": [1, 2, 3, 4, 5, 6, 7, 8, 9]
}


### 
POST https://localhost:7131/users 
Content-Type: application/json

{
 "name": "Barbara Sea Cow"
}

###
GET https://localhost:7204/users

###
PUT https://localhost:7131/users/462dd463-3dfd-41c8-be9f-52f5cb3489d0/name 
Content-Type: application/json 

{
    "name": "Barbara Manatee"
}